app:
  title: 'My reminder!'

spring:
  application:
    name: tray-app
  datasource:
    url: jdbc:h2:file:./data/traydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=create domain if not exists jsonb as text;
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  messages:
    basename: i18n/messages
    encoding: UTF-8
